/*
 * Generated by `payload generate:importmap`. This hand-written version pre-registers the Sirv
 * plugin's client components so the example runs out of the box. Re-run
 * `pnpm payload generate:importmap` after changing the component set (it overwrites this file).
 */
import {
  SirvAssetUrlField as SirvAssetUrlField_0,
  SirvMediaCell as SirvMediaCell_0,
  SirvMediaField as SirvMediaField_0,
  SirvMediaListCell as SirvMediaListCell_0,
  SirvMediaListField as SirvMediaListField_0,
  SirvNavLink as SirvNavLink_0,
  SirvSettingsView as SirvSettingsView_0,
} from '@sirv/payload-plugin/client';

export const importMap = {
  '@sirv/payload-plugin/client#SirvSettingsView': SirvSettingsView_0,
  '@sirv/payload-plugin/client#SirvNavLink': SirvNavLink_0,
  '@sirv/payload-plugin/client#SirvMediaField': SirvMediaField_0,
  '@sirv/payload-plugin/client#SirvMediaCell': SirvMediaCell_0,
  '@sirv/payload-plugin/client#SirvMediaListField': SirvMediaListField_0,
  '@sirv/payload-plugin/client#SirvMediaListCell': SirvMediaListCell_0,
  '@sirv/payload-plugin/client#SirvAssetUrlField': SirvAssetUrlField_0,
};
